name: ratkpcontext
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - torch==2.11.0
      - torch-geometric==2.7.0
      - lightning==2.6.1
      - chemprop==2.2.3
      - rdkit==2026.3.1
      - pandas==3.0.3
      - numpy==2.4.4
      - scipy==1.17.1
      - scikit-learn==1.8.0
      - xgboost==3.2.0
      - matplotlib==3.10.9
      - pillow==12.2.0
